/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const InProgressRun = IDL.Record({
  'timeElapsed' : IDL.Nat,
  'livesRemaining' : IDL.Nat,
  'currentLevel' : IDL.Nat,
  'currentScore' : IDL.Nat,
});
export const GameStats = IDL.Record({
  'highScore' : IDL.Nat,
  'lastCompletedLevel' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearInProgressRun' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInProgressRun' : IDL.Func([], [IDL.Opt(InProgressRun)], ['query']),
  'getPlayerStats' : IDL.Func([IDL.Principal], [IDL.Opt(GameStats)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasInProgressRun' : IDL.Func([], [IDL.Bool], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loadStats' : IDL.Func([], [IDL.Opt(GameStats)], ['query']),
  'resetPlayerStats' : IDL.Func([IDL.Principal], [], []),
  'resetStats' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveInProgressRun' : IDL.Func([InProgressRun], [], []),
  'saveStats' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const InProgressRun = IDL.Record({
    'timeElapsed' : IDL.Nat,
    'livesRemaining' : IDL.Nat,
    'currentLevel' : IDL.Nat,
    'currentScore' : IDL.Nat,
  });
  const GameStats = IDL.Record({
    'highScore' : IDL.Nat,
    'lastCompletedLevel' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearInProgressRun' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInProgressRun' : IDL.Func([], [IDL.Opt(InProgressRun)], ['query']),
    'getPlayerStats' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(GameStats)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasInProgressRun' : IDL.Func([], [IDL.Bool], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loadStats' : IDL.Func([], [IDL.Opt(GameStats)], ['query']),
    'resetPlayerStats' : IDL.Func([IDL.Principal], [], []),
    'resetStats' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveInProgressRun' : IDL.Func([InProgressRun], [], []),
    'saveStats' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };